{
  imports = [
    ./emulation.nix
    ./packages.nix
    ./fastfetch.nix
    ./fish.nix
    ./flatpak.nix
    ./foot.nix
    ./fzf.nix
    ./ghostty.nix
    ./gtk-qt.nix
    ./hypr
    ./nvim
    ./mako.nix
    ./rofi.nix
    ./starship.nix
    ./stylix.nix
    ./swappy.nix
    ./text-editor.nix
    ./tmux.nix
    ./waybar.nix
    ./wezterm.nix
  ];
}
